export const FETCH_ALL_HERO = 'FETCH_ALL_HERO'
export const FETCH_SINGLE_HERO_BY_ID = 'FETCH_SINGLE_HERO_BY_ID'
export const UPDATE_HERO_BY_ID = 'UPDATE_HERO_BY_ID'
export const CHANGE_THEME = 'CHANGE_THEME'
